app/urls.py
from django.conf.urls.defaults import patterns, include, url
from cabotapp.views import (run_status_check, update_service,
    graphite_api_data, twiml_callback, checks_run_recently,
    GraphiteCheckCreateView, GraphiteCheckUpdateView,
    HttpCheckCreateView, HttpCheckUpdateView,
    JenkinsCheckCreateView, JenkinsCheckUpdateView,
    StatusCheckDeleteView, StatusCheckListView, StatusCheckDetailView,
    StatusCheckResultDetailView)
from cabotapp.views import (ServiceListView, ServiceDetailView,
    ServiceUpdateView, ServiceCreateView, ServiceDeleteView,
    UserProfileUpdateView, ShiftListView, subscriptions)
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', view=RedirectView.as_view(url='services/', permanent=False), name='dashboard'),
    url(r'^subscriptions/', view=subscriptions, name='subscriptions'),
    url(r'^accounts/login/', view=login, name='login'),
    url(r'^accounts/logout/', view=logout, name='logout'),
    url(r'^accounts/password-reset/', view=password_reset, name='password-reset'),
    url(r'^accounts/password-reset-done/', view=password_reset_done, name='password-reset-done'),
    url(r'^accounts/password-reset-confirm/', view=password_reset_confirm, name='password-reset-confirm'),
    url(r'^status/', view=checks_run_recently, name='system-status'),

    url(r'^services/', view=ServiceListView.as_view(), name='services'),
    url(r'^service/create/', view=ServiceCreateView.as_view(), name='create-service'),
    url(r'^service/update/(?P<pk>\d+)/', view=ServiceUpdateView.as_view(), name='update-service'),
    url(r'^service/delete/(?P<pk>\d+)/', view=ServiceDeleteView.as_view(), name='delete-service'),
    url(r'^service/(?P<pk>\d+)/', view=ServiceDetailView.as_view(), name='service'),
    url(r'^service/run_service_update/(?P<pk>\d+)/', view=update_service, name='run-service-update'),

    url(r'^checks/', view=StatusCheckListView.as_view(), name='checks'),
    url(r'^check/run/(?P<pk>\d+)/', view=run_status_check, name='run-check'),
    url(r'^check/delete/(?P<pk>\d+)/', view=StatusCheckDeleteView.as_view(), name='delete-check'),
    url(r'^check/(?P<pk>\d+)/', view=StatusCheckDetailView.as_view(), name='check'),

    url(r'^graphitecheck/create/', view=GraphiteCheckCreateView.as_view(), name='create-check'),
    url(r'^graphitecheck/update/(?P<pk>\d+)/', view=GraphiteCheckUpdateView.as_view(), name='update-check'),
    url(r'^httpcheck/create/', view=HttpCheckCreateView.as_view(), name='create-http-check'),
    url(r'^httpcheck/update/(?P<pk>\d+)/', view=HttpCheckUpdateView.as_view(), name='update-http-check'),
    url(r'^jenkins_check/create/', view=JenkinsCheckCreateView.as_view(), name='create-jenkins-check'),
    url(r'^jenkins_check/update/(?P<pk>\d+)/', view=JenkinsCheckUpdateView.as_view(), name='update-jenkins-check'),

    url(r'^result/(?P<service_id>\d+)/twiml_callback/', view=twiml_callback, name='twiml-callback'),
    url(r'^result/(?P<pk>\d+)/', view=StatusCheckResultDetailView.as_view(), name='result'),

    url(r'^shifts/', view=ShiftListView.as_view(), name='shifts'),

    url(r'^graphite/', view=graphite_api_data, name='graphite-data'),

    url(r'^user/(?P<pk>\d+)/profile/', view=UserProfileUpdateView.as_view(), name='user-profile'),
    url(r'^admin/', include(admin.site.urls)),
)

app/cabotapp/models.py
from django.db import models
from django.conf import settings
from polymorphic import PolymorphicModel
from django.db.models import F
from django.contrib.admin.models import User

from jenkins import get_job_status
from .alert import send_alert
from .calendar import get_events
from .graphite import parse_metric
from .alert import send_alert
from datetime import datetime, timedelta
from django.utils import timezone

import json
import re
import time

import requests
from celery.utils.log import get_task_logger

logger = get_task_logger(__name__)

CHECK_TYPES = (
    ('>', 'Greater than'),
    ('>=', 'Greater than or equal'),
    ('<', 'Less than'),
    ('<=', 'Less than or equal'),
    ('==', 'Equal to'),
)


def serialize_recent_results(recent_results):
    if not recent_results:
        return ''

    def result_to_value(result):
        if result.succeeded:
            return '1'
        else:
            return '-1'
    vals = [result_to_value(r) for r in recent_results]
    vals.reverse()
    return ','.join(vals)


def calculate_debounced_passing(recent_results, debounce=0):
    """
    `debounce` is the number of previous failures we need (not including this)
    to mark a search as passing or failing
    Returns:
      True if passing given debounce factor
      False if failing
    """
    if not recent_results:
        return True
    debounce_window = recent_results[:debounce + 1]
    for r in debounce_window:
        if r.succeeded:
            return True
    return False


class Service(models.Model):
    PASSING_STATUS = 'PASSING'
    WARNING_STATUS = 'WARNING'
    ERROR_STATUS = 'ERROR'
    CRITICAL_STATUS = 'CRITICAL'

    CALCULATED_PASSING_STATUS = 'passing'
    CALCULATED_INTERMITTENT_STATUS = 'intermittent'
    CALCULATED_FAILING_STATUS = 'failing'

    STATUSES = (
        (CALCULATED_PASSING_STATUS, CALCULATED_PASSING_STATUS),
        (CALCULATED_INTERMITTENT_STATUS, CALCULATED_INTERMITTENT_STATUS),
        (CALCULATED_FAILING_STATUS, CALCULATED_FAILING_STATUS),
    )

    IMPORTANCES = (
        (WARNING_STATUS, 'Warning'),
        (ERROR_STATUS, 'Error'),
        (CRITICAL_STATUS, 'Critical'),
    )

    name = models.TextField()
    url = models.TextField(
        blank=True,
        help_text="URL of service."
    )
    users_to_notify = models.ManyToManyField(
        User,
        blank=True,
        help_text='Users who should receive alerts.',
    )
    status_checks = models.ManyToManyField(
        'StatusCheck',
        blank=True,
        help_text='Checks used to calculate service status.',
    )
    last_alert_sent = models.DateTimeField(
        null=True,
        blank=True,
    )
    email_alert = models.BooleanField(default=False)
    hipchat_alert = models.BooleanField(default=True)
    sms_alert = models.BooleanField(default=False)
    telephone_alert = models.BooleanField(
        default=False,
        help_text='Must be enabled, and check importance set to Critical, to receive telephone alerts.',
    )
    alerts_enabled = models.BooleanField(
        default=True,
        help_text='Alert when this service is not healthy.',
    )
    overall_status = models.TextField(default=PASSING_STATUS)
    old_overall_status = models.TextField(default=PASSING_STATUS)
    hackpad_id = models.TextField(
        null=True,
        blank=True,
        help_text='Alphanumeric id of Hackpad containing recovery information.'
    )

    class Meta:
        ordering = ['name']

    def __unicode__(self):
        return self.name

    def update_status(self):
        self.old_overall_status = self.overall_status
        # Only active checks feed into our calculation
        status_checks_failed_count = self.all_failing_checks().count()
        self.overall_status = self.most_severe(self.all_failing_checks())
        self.snapshot = ServiceStatusSnapshot(
            service=self,
            num_checks_active=self.active_status_checks().count(),
            num_checks_passing=self.active_status_checks().count() - status_checks_failed_count,
            num_checks_failing=status_checks_failed_count,
            overall_status=self.overall_status,
            time=timezone.now(),
        )
        self.snapshot.save()
        self.save()
        if not (self.overall_status == Service.PASSING_STATUS and self.old_overall_status == Service.PASSING_STATUS):
            self.alert()

    def most_severe(self, check_list):
        failures = [c.importance for c in check_list]
        if self.CRITICAL_STATUS in failures:
            return self.CRITICAL_STATUS
        if self.ERROR_STATUS in failures:
            return self.ERROR_STATUS
        if self.WARNING_STATUS in failures:
            return self.WARNING_STATUS
        return self.PASSING_STATUS

    @property
    def is_critical(self):
        """
        Break out separately because it's a bit of a pain to
        get wrong.
        """
        if self.old_overall_status != self.CRITICAL_STATUS and self.overall_status == self.CRITICAL_STATUS:
            return True
        return False

    def alert(self):
        if not self.alerts_enabled:
            return
        if self.overall_status != self.PASSING_STATUS:
            # Don't alert every time
            if self.overall_status == self.WARNING_STATUS:
                if self.last_alert_sent and (timezone.now() - timedelta(minutes=settings.NOTIFICATION_INTERVAL)) < self.last_alert_sent:
                    return
            elif self.overall_status in (self.CRITICAL_STATUS, self.ERROR_STATUS):
                if self.last_alert_sent and (timezone.now() - timedelta(minutes=settings.ALERT_INTERVAL)) < self.last_alert_sent:
                    return
            self.last_alert_sent = timezone.now()
        else:
            self.last_alert_sent = None  # We don't count "back to normal" as an alert
        self.save()
        self.snapshot.did_send_alert = True
        self.snapshot.save()
        # send_alert handles the logic of how exactly alerts should be handled
        send_alert(self, duty_officers=get_duty_officers())

    @property
    def recent_snapshots(self):
        snapshots = self.snapshots.filter(time__gt=(timezone.now() - timedelta(minutes=60 * 4)))
        snapshots = list(snapshots.values())
        for s in snapshots:
            s['time'] = time.mktime(s['time'].timetuple())
        return snapshots

    def active_status_checks(self):
        return self.status_checks.filter(active=True)

    def inactive_status_checks(self):
        return self.status_checks.filter(active=False)

    def all_passing_checks(self):
        return self.active_status_checks().filter(calculated_status=self.CALCULATED_PASSING_STATUS)

    def all_failing_checks(self):
        return self.active_status_checks().exclude(calculated_status=self.CALCULATED_PASSING_STATUS)

    def graphite_status_checks(self):
        return self.status_checks.filter(polymorphic_ctype__model='graphitestatuscheck')

    def http_status_checks(self):
        return self.status_checks.filter(polymorphic_ctype__model='httpstatuscheck')

    def jenkins_status_checks(self):
        return self.status_checks.filter(polymorphic_ctype__model='jenkinsstatuscheck')

    def active_graphite_status_checks(self):
        return self.graphite_status_checks().filter(active=True)

    def active_http_status_checks(self):
        return self.http_status_checks().filter(active=True)

    def active_jenkins_status_checks(self):
        return self.jenkins_status_checks().filter(active=True)


class ServiceStatusSnapshot(models.Model):
    service = models.ForeignKey(Service, related_name='snapshots')
    time = models.DateTimeField()
    num_checks_active = models.IntegerField(default=0)
    num_checks_passing = models.IntegerField(default=0)
    num_checks_failing = models.IntegerField(default=0)
    overall_status = models.TextField(default=Service.PASSING_STATUS)
    did_send_alert = models.IntegerField(default=False)

    def __unicode__(self):
        return u"%s: %s" % (self.service.name, self.overall_status)


class StatusCheck(PolymorphicModel):

    """
    Base class for polymorphic models. We're going to use
    proxy models for inheriting because it makes life much simpler,
    but this allows us to stick different methods etc on subclasses.

    You can work out what (sub)class a model is an instance of by accessing `instance.polymorphic_ctype.model`

    We are using django-polymorphic for polymorphism
    """

    # Common attributes to all
    name = models.TextField()
    active = models.BooleanField(
        default=True,
        help_text='If not active, check will not be used to calculate service status and will not trigger alerts.',
    )
    importance = models.CharField(
        max_length=30,
        choices=Service.IMPORTANCES,
        default=Service.ERROR_STATUS,
        help_text='Severity level of a failure. Critical alerts are for failures you want to wake you up at 2am, Errors are things you can sleep through but need to fix in the morning, and warnings for less important things.'
    )
    frequency = models.IntegerField(
        default=5,
        help_text='Minutes between each check.',
    )
    debounce = models.IntegerField(
        default=0,
        null=True,
        help_text='Number of successive failures permitted before check will be marked as failed. Default is 0, i.e. fail on first failure.'
    )
    created_by = models.ForeignKey(User)
    calculated_status = models.CharField(
        max_length=50, choices=Service.STATUSES, default=Service.CALCULATED_PASSING_STATUS, blank=True)
    last_run = models.DateTimeField(null=True)
    cached_health = models.TextField(editable=False, null=True)

    # Graphite checks
    metric = models.TextField(
        null=True,
        help_text='fully.qualified.name of the Graphite metric you want to watch. This can be any valid Graphite expression, including wildcards, multiple hosts, etc.',
    )
    check_type = models.CharField(

app/templates/cabotapp/_base_form.html
<div class="form-group">
  <div class="col-xs-10 col-xs-offset-2">
    {{ form.non_field_errors }}
  </div>
</div>
{% csrf_token %}
{% for field in form %}
<div class="form-group{% if field.errors %} has-error{% endif %}">
  <div class="col-xs-12">
    <label class="col-xs-2 control-label">{{ field.label_tag }}</label>
    {% if field.errors %}
    <div class="col-xs-7">{{ field }}</div>
    <div class="col-xs-3 alert alert-danger">{{ field.errors }}</div>
    {% else %}
    <div class="col-xs-10">{{ field }}</div>
    {% endif %}
  </div>
  {% if field.name == 'metric' %}
  <div class="col-xs-12">
    <div class="col-xs-10 col-xs-offset-2" id="graph" style="height:200px;"></div>
    <div class="col-xs-10 col-xs-offset-2">
      <pre id="graphite_data_container"></pre>
    </div>
  </div>
  {% else %}
  {% endif %}
  {% if field.help_text %}
  <div class="col-xs-12">
    <div class="col-xs-7 col-xs-offset-2"><p class="help-block">{{ field.help_text }}</p></div>
  </div>
  {% endif %}
</div>
{% endfor %}

app/templates/cabotapp/_statuscheck_list.html
{% load extra %}

<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-1"><h3><i class="{% if checks_type == "All" %}fa fa-cog{% else %}glyphicon glyphicon-{% if checks_type == "Http" %}arrow-up{% elif checks_type == "Jenkins" %}ok{% else %}signal{% endif %}{% endif %}"></i></h3></div>
    <div class="col-xs-8"><h3>{{ checks_type }} checks</h3></div>
    <div class="col-xs-3 text-right">
      <h3>
      &nbsp;{% if checks_type == "All" or checks_type == "Graphite" %}
      <a href="{% url create-check %}?service={{ service.id }}" class=""><i class="glyphicon glyphicon-plus" title="Add new metric check"></i><i class="glyphicon glyphicon-signal" title="Add new metric check"></i></a>
      {% endif %}
      {% if checks_type == "All" or checks_type == "Http" %}
      &nbsp;<a href="{% url create-http-check %}?service={{ service.id }}" class="" title="Add new Http check"><i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-arrow-up"></i></a>
      {% endif %}
      {% if checks_type == "All" or checks_type == "Jenkins" %}
      &nbsp;<a href="{% url create-jenkins-check %}?service={{ service.id }}" class="" title="Add new Jenkins check"><i class="glyphicon glyphicon-plus"></i><i class="glyphicon glyphicon-ok"></i></a>
      {% endif %}
      </h3>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12">
    {% if not checks %}
      <div class="col-xs-11 col-xs-offset-1">No checks configured</div>
    {% else %}
    <table class="table table-bordered bootstrap-datatable datatable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Status</th>
          {% if checks_type == "All" %}
          <th>Type</th>
          {% endif %}
          <th>Test description</th>
          <th>Health</th>
          <th>Importance</th>
          <th>Service(s)</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for check in checks %}
        <tr class="{% if check.active %}enabled{% else %}warning{% endif %}">
          <td title="{{ check.description }} - alerts {% if check.active %}enabled{% else %}disabled{% endif %}">
            <a href="{% url check pk=check.id %}">{{check.name}}</a>
          </td>
          <td title="{{ check.calculated_status }}">
            {% if check.active %}
            <span class="label label-{% if check.calculated_status == 'passing' %}success{% else %}danger{% endif %}">
              {{ check.calculated_status|capfirst }}
            </span>
            {% else %}
            <span class="label label-warning">Disabled</span>
            {% endif %}
          </td>
          {% if checks_type == "All" %}
          <td>
          <i class="glyphicon glyphicon-{% if check.polymorphic_ctype.model == 'graphitestatuscheck' %}signal{% elif check.polymorphic_ctype.model == 'httpstatuscheck' %}arrow-up{% elif check.polymorphic_ctype.model == 'jenkinsstatuscheck' %}ok{% endif %}"></i>
          </td>
          {% endif %}
          <td title="">
            {% if check.polymorphic_ctype.model == 'graphitestatuscheck' %}{{ check.metric|truncatechars:70 }} {{ check.check_type }} {{ check.value }}{% if check.expected_num_hosts %} (from {{ check.expected_num_hosts }} hosts){% endif %}{% elif check.polymorphic_ctype.model == 'httpstatuscheck' %}Status code {{ check.status_code }} from {{ check.endpoint }}{% if check.text_match %}; match text /{{ check.text_match }}/{% endif %}{% elif check.polymorphic_ctype.model == 'jenkinsstatuscheck' %}Monitor job {{ check.name }}{% if check.max_queued_build_time %}; check no build waiting for >{{ check.max_queued_build_time }} minutes{% endif %}{% endif %}
          </td>
          <td title="Last result from {{ check.last_run|timesince }} ago (rightmost is newest)" class="text-right">
            {% if not check.recent_results %}
            No results available
            {% endif %}
            <a href="{% url check pk=check.id %}">
              <span class="sparktristate">
                {{ check.cached_health }}
              </span>
            </a>
          </td>
          <td>{{ check.get_importance_display }}</td>
          <td>
            {% for service in check.service_set.all %}
            <a href="{% url service pk=service.id %}">{{ service.name }}</a>
            {% if forloop.last %}
            {% else %}
            /
            {% endif %}
            {% endfor %}
            {% if not check.service_set.all %}
            <span class="label label-warning">No service</span>
            {% endif %}
          </td>
          <td class="text-right">
            <a class="btn btn-xs" href="{% if check.polymorphic_ctype.model == 'graphitestatuscheck' %}{% url update-check pk=check.id %}{% elif check.polymorphic_ctype.model == 'httpstatuscheck' %}{% url update-http-check pk=check.id %}{% elif check.polymorphic_ctype.model == 'jenkinsstatuscheck' %}{% url update-jenkins-check pk=check.id %}{% endif %}">
              <i class="glyphicon glyphicon-edit"></i><span class="break"></span>
            </a>
            <a class="btn btn-xs" href="{% url run-check pk=check.id %}">
              <i class="glyphicon glyphicon-refresh"></i><span class="break"></span>
            </a>
            {% if checks_type == "Jenkins" %}
            <a class="btn btn-xs" href="{% jenkins_human_url check.name %}">
              <i class="glyphicon glyphicon-link"></i><span class="break"></span>
            </a>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>

app/templates/cabotapp/service_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete service</h1>
<form action="." method="post">{% csrf_token %}
  <button type="submit" class="btn btn-danger">Delete {{ object }}</button>
</form>
{% endblock %}

{% load compress %}
{% block js %}
{{ block.super }}
{% compress js %}
<script type="text/coffeescript">

</script>
{% endcompress %}
{% endblock %}

app/templates/cabotapp/service_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-10 col-xs-offset-2">
      <h2>{% if form.instance.id %}Edit service{% else %}New service{% endif %}</h2>
    </div>
  </div>
</div>
<form class="form-horizontal" action="" method="post" role="form">
  {% include "cabotapp/_base_form.html" %}
  <div class="col-xs-12">
    <div class="form-group">
      <div class="col-xs-6 col-xs-offset-2">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url dashboard %}" class="btn">Back to dashboard</a>
      </div>
      {% if form.instance.id %}
      <div class="col-xs-4">
        <a class="btn btn-danger" href="{% url delete-service form.instance.id %}">Delete service</a>
      </div>
      {% endif %}
      </div>
    </div>
  </form>
</form>
{% endblock %}

{% load compress %}
{% block js %}
{{ block.super }}
{% compress js %}
<script type="text/coffeescript">
</script>
{% endcompress %}
{% endblock %}

app/templates/cabotapp/statuscheck_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-1"><h2><i class="glyphicon glyphicon-{% if check.polymorphic_ctype.model == 'graphitestatuscheck' %}signal{% elif check.polymorphic_ctype.model == 'httpstatuscheck' %}arrow-up{% elif check.polymorphic_ctype.model == 'jenkinsstatuscheck' %}ok{% endif %}"></i></h2></div>
    <div class="col-xs-5"><h2>{{ check.name }}</h2></div>
    <div class="col-xs-4 text-right"><h2><span class="label label-{% if check.calculated_status == 'passing' %}success{% else %}danger{% endif %}">{{ check.calculated_status|capfirst }}</span></h2></div>
    <div class="col-xs-2 text-right"><h2><a href="{% if check.polymorphic_ctype.model == 'graphitestatuscheck' %}{% url update-check pk=check.id %}{% elif check.polymorphic_ctype.model == 'httpstatuscheck' %}{% url update-http-check pk=check.id %}{% elif check.polymorphic_ctype.model == 'jenkinsstatuscheck' %}{% url update-jenkins-check pk=check.id %}{% endif %}" class=""><i class="glyphicon glyphicon-edit"></i></a> <a href="{% url run-check pk=check.id %}"><i class="glyphicon glyphicon-refresh"></i></a></h2></div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-1"><h3><i class="fa fa-list"></i></h3></div>
    <div class="col-xs-11"><h3>Check results</h3></div>
  </div>
  <div class="col-xs-12">
    {% if not checkresults %}
      <div class="col-xs-11 col-xs-offset-1">No results for this check</div>
    {% else %}
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Status</th>
          <th>Time started</th>
          <th>Time complete</th>
          <th>Took</th>
          <th>Error</th>
        </tr>
      </thead>
      <tbody>
      {% for result in checkresults %}
        <tr>
          <td>
            <span class="label {% if result.succeeded %}label-success{% else %}label-danger{% endif %}">{{ result.status }}
            </span>
          </td>
          <td>
            <a href="{% url result pk=result.id %}">{{ result.time }}</a>
          </td>
          <td>{{ result.time_complete }}</td>
          <td>{{ result.took }}</td>
          <td>{{ result.error }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</div>
<hr>
<div class="row">
  {% for service in check.service_set.all %}
  {% if service.hackpad_id %}
  <div class="col-xs-12">
    <div class="col-xs-1"><h3><i class="fa fa-exclamation-triangle"></i></h3></div>
    <div class="col-xs-11"><h3>Recovery instructions for linked service <a href="{% url service service.id %}">{{ service.name }}</a></h3></div>
    <div class="col-xs-12">
      <script src="https://arachnys.hackpad.com/{{ service.hackpad_id }}.js"></script>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock content %}

{% block js %}
{% load compress %}
{{ block.super }}
{% compress js %}
<script type="text/coffeescript">

</script>
{% endcompress %}
{% endblock js %}

app/templates/cabotapp/statuscheck_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-xs-12">
    <div class="col-xs-10 col-xs-offset-2">
      <h2>{% if form.instance.id %}Edit check{% else %}New check{% endif %}</h2>
    </div>
  </div>
</div>
<form class="form-horizontal" action="" method="post" role="form">
  {% include "cabotapp/_base_form.html" %}
  <div class="col-xs-12">
    <div class="form-group">
      <div class="col-xs-6 col-xs-offset-2">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{% url dashboard %}" class="btn">Back to dashboard</a>
      </div>
      {% if form.instance.id %}
      <div class="col-xs-4">
        <a class="btn btn-danger" href="{% url delete-check form.instance.id %}">Delete check</a>
      </div>
      {% endif %}
      </div>
    </div>
  </div>
</form>
{% endblock %}

{% load compress %}
{% block js %}
{{ block.super }}
{% compress js %}
<script type="text/coffeescript">
GRAPHITE_ENDPOINT = '/graphite/'

$(document).ready ->
  updateGraphiteData()
  $('#id_metric').on('keyup', updateGraphiteData)

  $('#id_metric').autocomplete
    source: (request, response) ->
      $.ajax
        url: GRAPHITE_ENDPOINT
        data:
          metric: request.term
      .done (data) ->
        metricList = data.matchingMetrics?.metrics?.metrics
        if metricList
          metrics = (m.path for m in metricList)
          response metrics
    minLength: 0
    close: (evt, ui) ->
      if $('#id_metric').is(':focus')
        $('#id_metric').autocomplete("search", $('#id_metric').val())

updateGraphiteData = () ->
  $('#graphite_data_container').text 'Getting data'
  m = $('#id_metric').val()
  $.ajax
    url: GRAPHITE_ENDPOINT
    data:
      metric: m
  .done (data) ->
    if data.data? and data.data.length? != 0
      $('#graphite_data_container').text JSON.stringify(data.data, undefined, 2)
      drawMorris data.data
    else
      $('#graphite_data_container').text 'Select a valid metric'
      removeMorris()

drawMorris = (data) ->
  kvs = []
  labels = []
  $('#graph').show()
  all = {}
  for series in data
    label = series.target
    labels.push label
    for point in series.datapoints
      t = point[1]*1000
      if not all[t]?
        all[t] = {}
      all[t][label] = point[0]
  for k, v of all
    tmp = {time: parseInt(k)}
    for k2, v2 of v
      tmp[k2] = v2
    kvs.push tmp

  $('#graph').empty()
  if not kvs
    return
  window.morrisLine = Morris.Line
    element: 'graph'
    data: kvs
    xkey: 'time'
    ykeys: labels
    labels: (label[0..10] + '...' + label[-10..] for label in labels)
    hideHover: 'auto'

removeMorris = () ->
  $('#graph').hide()

</script>
{% endcompress %}
{% endblock %}